---
title: "Prioritization of cropland restoration"
author: "Nick McManus"
date: '2022-10-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(prioritizr)    # optimization software! 
library(terra)         # for reading in and altering rasters
library(sf)
library(raster)
library(tidyverse)     # always!
library(rnaturalearth) # administrative boundaries data
library(rnaturalearthdata)
```

## Read in data

```{r}
# read in the cropland abandonment
ssp1_abandoned_crop <- rast("data/inputs/SSP1_abandoned_cropland_brazil.tif")
ssp2_abandoned_crop <- rast("data/inputs/SSP2_abandoned_cropland_brazil.tif")
ssp3_abandoned_crop <- rast("data/inputs/SSP3_abandoned_cropland_brazil.tif")
ssp4_abandoned_crop <- rast("data/inputs/SSP4_abandoned_cropland_brazil.tif")
ssp5_abandoned_crop <- rast("data/inputs/SSP5_abandoned_cropland_brazil.tif")

# read in carbon layer
carbon <- rast("data/inputs/sequestration_rate_mean_aboveground_full_extent_Mg_C_ha_yr.tif")
```

```{r}
plot(carbon)

# crop to Brazil
brazil <- ne_countries(
  scale = "medium",
  country = "Brazil",
  returnclass = "sf") %>% 
  dplyr::select(sovereignt)

ggplot() +
  geom_sf(data = brazil)

# Transform Brazil to Carbon raster

brazil_trans <- brazil %>% 
  st_transform(crs = crs(carbon)) %>% 
  vect()

# Crop carbon data
carbon_crop <- carbon %>% 
  crop(brazil_trans) %>% 
  mask(brazil_trans) %>% 
  terra::project(y = crs(brazil))

plot(carbon_crop)

#export carbon_crop

writeRaster(carbon_crop, "data/outputs/carbon_seq_rate_Brazil.tif")
```

